import type { Metadata } from "next";
import { Rubik } from "next/font/google";
import "./globals.css";

const rubi = Rubik({
  subsets: ["latin"],
  variable: "--font-rubik",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${rubi.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
